# Site
name: Fastcfs
description: FastCFS is a high performance distributed file storage system.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl:
disqus: fastcfs
email: zhangchunsheng423@gmail.com
mailchimp-list: https://zhangchunsheng.us4.list-manage.com/subscribe/post?u=&amp;id=

include: ["_pages"]
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: _posts
    values:
      layout: post
      comments: true
      author: fastcfs
      avatar: /assets/developers/fastcfs/logo.png

  # all pages
  - scope:
      path: _pages
    values:
      layout: page
  - scope:
      path: _developers
    values:
      layout: developer
      comments: true

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 30
paginate_path: /blog/page:num/

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  - package.json
  - _site
  - node_modules

collections:
  developers:
    output: true
    permalink: /:collection/:path/
